#!/bin/bash

#==============================#
# Quantum Espresso Job Writter #
#       - for ADA -            #
#==============================#

#------------------------------
#
#
#
#
#------------------------------


#--------
# Inputs
#--------------------------------
#  - localworkdir
#  - structure_name
#  - sim_type
#  - VdW_corr
#  - pres_value
#  - temp_value
#  - ecutwfc
#  - ecutrho
#  - n_cores
#  - n_seconds
#--------------------------------

run=$structure_name"."$sim_type

if [[ $VdW_corr != "" ]]
then
    run=$run"."$VdW_corr
fi
if [[ $pres_value != "" ]]
then
    run=$run"."$pres_value"kbar"
fi
if [[ $temp_value != "" ]]
then
    run=$run"."$temp_value"K"
fi
run=$run"."$ecutwfc"Ry."$ecutrho"Ry.out"


cat > $localworkdir"/run" <<EOF
# @ shell = /bin/csh
# @ job_name = $structure_name
# @ job_type = parallel
# @ output = \$(job_name).\$(jobid)
# @ error = \$(job_name).\$(jobid)
# @ wall_clock_limit = $n_seconds
# @ total_tasks = $n_cores
# @ queue

set echo

module load espresso/5.3.0

cd \$TMPDIR

cp $localworkdir/* .

poe pw.x < pw.d > $run

cp -r \$TMPDIR/* $localworkdir

cd $localworkdir

rm -r *wfc* *.save 

EOF
