#!/bin/bash

name="mo4s8"

if [ -e data_"$name".xyz ]
then
   rm data_"$name".xyz
fi
   
awk '$1=="ATOMIC_POSITIONS" || $1=="Mo" || $1=="S" && $2!="6.00" && $2!="14.00"
' MoS2.out  > test2

typeset -i i=0

while read line
do
if [ "$line" == "ATOMIC_POSITIONS (angstrom)" ]
then
i=$i+1
echo -e '12\nstep '$i >> "$name".xyz
else
echo $line >> "$name".xyz
fi
done < test2

rm test2

sed "s/Mo 14.00 95.96000 Mo( 1.00)//g" -i "$name".xyz
sed '/^$/d' -i "$name".xyz
