#!/bin/bash

echo -e "Starting!"

# Loop over all the arguments
for file in "$@"
do
    # Checking file existence
    if [ ! -f $file ]
    then
       echo "File "$file" not found in "$(pwd)" !"
       continue 
    fi
    # Start message
    echo "Handling "$file
    # Getting name of the file, extracting the extension
    filename=$( echo $file | cut -d "." -f1 )
    # Name of outfile
    out=$filename".cpmd"
    # Removing previous file if exists
    if [ -e $out ]
    then
	rm $out
    fi
    # Storing atoms in their files
    awk '{if( $1 == "O" ){print $2," ",$3," ",$4}}' $file > Otemp
    awk '{if( $1 == "C" ){print $2," ",$3," ",$4}}' $file > Ctemp
    if [ ! -e Otemp ]
    then
	echo "Something went wrong with "$file" (No Otemp file generated)!"
	if [ -e Ctemp ]
	then
	   rm Ctemp
	fi
	continue
    fi
    if [ ! -e Ctemp ]
    then
	echo "Something went wrong with "$file" (No Ctemp file generated)!"
	if [ -e Otemp ]
	then
	   rm Otemp
	fi
	continue
    fi
    # Putting it all together
    # C atom
    echo "C" > $out
    awk '{print}' Ctemp >> $out
    # O atom
    echo "O" >> $out
    awk '{print}' Otemp >> $out
    # Cleaning
    sed "s/,/./g" -i $out
    sed "s/,/./g" -i $file
    # Remove temp files
    rm Otemp
    rm Ctemp
done

echo "All Done."
