#!/bin/bash

echo -e "Starting!"

# Loop over all the arguments
for file in "$@"
do
    # Checking file existence
    if [ ! -f $file ]
    then
       echo "File "$file" not found in "$(pwd)" !"
       continue 
    fi
    # Cleaning
    sed "s/,/./g" -i $file
    # Start message
    echo "Handling "$file
    # Getting name of the file, extracting the extension
    filename=$( echo $file | cut -d "." -f1 )
    # Name of outfile
    out=$filename"_bond.input"
    # Removing previous file if exists
    if [ -e $out ]
    then
	rm $out
    fi
    # Storing atoms in their files
    awk '{if( $1 == "O" ){print $2," ",$3," ",$4}}' $file > Otemp
    awk '{if( $1 == "C" ){print $2," ",$3," ",$4}}' $file > Ctemp
    if [ ! -e Otemp ]
    then
	echo "Something went wrong with "$file" (No Otemp file generated)!"
	if [ -e Ctemp ]
	then
	   rm Ctemp
	fi
	continue
    fi
    if [ ! -e Ctemp ]
    then
	echo "Something went wrong with "$file" (No Ctemp file generated)!"
	if [ -e Otemp ]
	then
	   rm Otemp
	fi
	continue
    fi
    # Start file
    echo -e "LAMMPS data file \n" >> $out
    # Writting first elements
    echo "2592 atoms" >> $out
    echo -e "2 atom types\n" >> $out
    # Cell
    # Writting general file
    if [ -e temp ]
    then
	rm temp
    fi
    awk '{print}' Otemp > temp
    awk '{print}' Ctemp >> temp
    # Checking file
    if [ ! -e temp ]
    then
	"Something went wrong creating temp file for "$file" !"
    fi
    #====================================================
    # Cell
    #====================================================
    # Removing previous temp file if exists
    if [ -e cell ]
    then
	rm cell
    fi
    # Calling f90 "cell_lammps" program to make cell
    cell
    # Checking that everything went fine
    if [ ! -e cell ]
    then
	echo "Something went wrong making cell for "$file" !"
	continue 
    fi
    # Writting results
    awk '{print}' cell >> $out
    echo " " >> $out

    #====================================================
    # Masses
    #====================================================
    echo -e "MASSES\n" >> $out
    echo "1 12.011" >> $out
    echo -e "1 15.999\n" >> $out
    #====================================================
    # Atoms
    #=====================================================
    echo -e "Atoms\n" >> $out
    # Removing previous temp file if exists
    if [ -e molecule ]
    then
	rm molecule
    fi
    # Calling f90 to make molecules
    molecules
    # Checking that everything went fine
    if [ ! -e molecule ]
    then
	echo "Something went wrong making atoms for "$file" !"
	continue
    fi
    # printing the content of molecules in outfile
    awk '{print}' molecule >> $out
    #====================================================
    # Bonds (depends on molecules)
    #====================================================
    echo " " >> $out
    # Checking that everything went fine
    if [ ! -e bond ]
    then
	echo "Something went wrong making bonds for "$file" !"
	continue
    fi
    # printing basic
    echo -e "Bonds\n" >> $out
    # printing the content of molecules in outfile
    awk '{print}' bond >> $out
    #========================================================
    # Trash
    #=======================================================
    rm molecule bond cell temp Otemp Ctemp
    #=======================================================
done

echo "All Done."
