#!/bin/bash

# Basics
cat 1-run/EKS_base > EKS_all.dat
cat 1-run/EClass_base > EClass_all.dat
cat 1-run/Time_base > Time_all.dat
cat 1-run/Temp_base > Temp_all.dat


# Second run
if [ -e "2-run/Time_base" ]
then
cat 2-run/Time_base >> Time_all.dat
cat 2-run/EClass_base >> EClass_all.dat
cat 2-run/EKS_base >> EKS_all.dat
cat 2-run/Temp_base >> Temp_all.dat
fi

# Third run
if [ -e "3-run/Time_base" ]
then
cat 3-run/Time_base >> Time_all.dat
cat 3-run/EClass_base >> EClass_all.dat
cat 3-run/EKS_base >> EKS_all.dat
cat 3-run/Temp_base >> Temp_all.dat
fi

# Fourth run
if [ -e "4-run/Time_base" ]
then
cat 4-run/Time_base >> Time_all.dat
cat 4-run/EClass_base >> EClass_all.dat
cat 4-run/EKS_base >> EKS_all.dat
cat 4-run/Temp_base >> Temp_all.dat
fi