#!/bin/bash
# @ job_name = Relax_test
# @ output = $(job_name).$(jobid)
# @ error = $(job_name).$(jobid)
# @ job_type = parallel
# @ total_tasks = 8
# @ wall_clock_limit = 2:00:00
# @ queue


# Loading quantum espresso
module load espresso/5.3.0

# Parameters
ecut="80"     # Cut-Off energy for wavefunction
ecutrho="500" # Cut-Off energy for density

set -x

pwd=$(pwd)
	
cp -r ./* $TMPDIR
    
######################### VC-RELAX ##############################
    
cat > pw.d << ***
	
    &control
    calculation = 'vc-relax',
    restart_mode='from_scratch',
    prefix='amf.$run',
    pseudo_dir='/workgpfs/rech/tta/rtta966/Work/pseudo',
    tstress = .true.
    tprnfor = .true.
    outdir='./temp/'
    verbosity = 'high'
    /

    &system
    ibrav=0, 
    nat=2, ntyp=2,
    ecutwfc=$ecut,
    ecutrho=$ecutrho,
    /

    &electrons
    electron_maxstep = loutre_electron_maxstep
    mixing_mode = 'plain'
    mixing_beta = 0.3
    conv_thr =  1.0d-12
    /

    &ions
    /

    &cell                
    press=loutre_pres      # Pressure
    cell_factor=3.0   # Cell factor... taken large to make sure it converges
    /   
    
    ATOMIC_SPECIES
    C 12.0107  C.pbe-van_ak.UPF
    O 14.0067  O.pbe-van_ak.UPF

    ATOMIC_POSITIONS crystal
    C        0.000000000   0.000000000   0.000000000
    O        0.250000000   0.250000000   0.250000000

    K_POINTS automatic
    kx ky kz 1 1 1
***
    
poe pw.x < pw.d > CO2_P-4_2mnm.relax.$ecut.$ecutrho.$press.out

cp -r $TMPDIR/* $pwd
	    

