#!/bin/bash

for counter in 12 356 829
    echo "deadling with "$counter
      cd $counter"_structure/"
      cp ../*MT* .
      cp ../run .
      cp ../cpmd_intelmpi_openmp_plumed.x .
      ccc_msub -q skylake -A gch0304 run
      cd ..
      let counter+=1
done
