#!/bin/bash

counter=0
until [ $counter -gt 1000 ]; do
    echo "deadling with "$counter
    cd $counter"_structure/"
    cp ../cpmd2cube.x .
    ./cpmd2cube.x -dens -center ELF
    ./cpmd2cube.x -dens -center DENSITY
    cd ..
    let counter+=1
done
