#!/bin/bash

typeset -i nb_structures=0
typeset -i structure_i=0
adress="_structure/ELF.cube"

string="vmd "
for (( structure=0 ; structure<$nb_structures ; structure++ ))
do
    string="$string ""$structure""$adress"
done

$($string &)
