#!/bin/bash

# cleaned name for file
name="mo4s8"

# Checking if output file exists
output="output"
if [ ! -e $output ]
then
    output="md.out"
    if [ ! -e $output ]
    then
	echo "No output file to clean."
	exit
    fi
fi

# If file already exists, remove it
if [ -e data_"$name".xyz ]
then
   rm data_"$name".xyz
fi

# Gets only the atomic positions in temporary file
awk '$1=="ATOMIC_POSITIONS" || $1=="Mo" || $1=="S" && $2!="6.00" && $2!="14.00"
' $output  > test2


# Read temp file and writes properly formated date in file
typeset -i i=0
while read line
do
if [ "$line" == "ATOMIC_POSITIONS (angstrom)" ]
then
i=$i+1
echo -e '12\nstep '$i >> "$name".xyz
else
echo $line >> "$name".xyz
fi
done < test2

# Remove temp file
rm test2

# Final cleaning of file
sed "s/Mo 14.00 95.96000 Mo( 1.00)//g" -i "$name".xyz
sed '/^$/d' -i "$name".xyz
