#!/bin/bash

#============
# Making ELF 
#============

#=======================================
# Number of C atoms
typeset -i nb_C=32
# Number of O atoms
typeset -i nb_O=64
# Total number of atoms
typeset -i nb_atoms=nb_C+nb_O
# Box size
box_size="8.82"
# Pseudo name
pseudoC="*C_MT_PBE.psp  KLEINMAN-BYLANDER"
pseudoO="*O_MT_PBE.psp  KLEINMAN-BYLANDER"
# Input file name
input_file="elf.xyz"
# Number of Structures
nb_structure=12
#=======================================

# Numbers of structures in files
#for structure in {0..9..1}
for (( structure=0 ; structure<$nb_structure ; structure++ ))
do
    # Message
    echo "Structure "$structure
    # Folder Name
    folder=$structure"_structure"
    # Putting the box size
    cp input_general input
    sed "s/X/$box_size/g" -i input
    # Writting C atoms
    echo "$pseudoC" >> input
    echo " LMAX=P" >> input
    echo " "$nb_C >> input
    for (( atom_index=0; atom_index<$nb_C ; atom_index++ ))
    do
	typeset -i line_nb=$( echo "$structure * $nb_atoms + $atom_index + 1 + 2*( $structure + 1 )" | bc -l )
	line=$(sed -n "$line_nb p"  $input_file )
	X=$(echo $line | cut -d " " -f2 )
	Y=$(echo $line | cut -d " " -f3 )
	Z=$(echo $line | cut -d " " -f4 )
	echo $X" "$Y" "$Z >> input
    done
    # Writting O atoms
    echo "$pseudoO" >> input
    echo " LMAX=P" >> input
    echo " "$nb_O >> input
    for (( atom_index=0; atom_index<$nb_O ; atom_index++ ))
    do
	typeset -i line_nb=$( echo "$structure * $nb_atoms + $atom_index + $nb_C + 1 + 2*( $structure + 1 ) " | bc -l )
	line=$(sed -n "$line_nb p"  $input_file )
	X=$(echo $line | cut -d " " -f2 )
	Y=$(echo $line | cut -d " " -f3 )
	Z=$(echo $line | cut -d " " -f4 )
	echo $X" "$Y" "$Z >> input
    done
    # End of message
    echo "&END" >> input
    # Creating folder
    if [ ! -e $folder ] 
    then
	mkdir $folder
    fi
    # Moving all files
    cp run $folder
    mv input $folder
    cp *MT* $folder
    # Moving to the folder
    cd $folder
    # Launching simulation
    sbatch run
    # Moving back
    cd ..
done
